service: demo13

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    MYSQL_HOST: ${env:MYSQL_HOST, "serverlesscourse.cluster-celduna5zw68.us-east-1.rds.amazonaws.com"}
    MYSQL_PORT: ${env:MYSQL_PORT, "3306"}
    MYSQL_USER: ${env:MYSQL_USER, "devleandrodias"}
    MYSQL_PASS: ${env:MYSQL_PASS, "abc12345"}
    MYSQL_DATABASE: ${env:MYSQL_DATABASE, "heroes"}
  vpc:
    securityGroupIds:
      - sg-0242e08a522422995
    subnetIds:
      - subnet-05341bfc96a9ee872
      - subnet-0cef30b2469bb9812
      - subnet-00ecaa9f353e409ae
      - subnet-09f3675b7f60d0dd8
      - subnet-029531f1cda9648e7
      - subnet-009cae755e41dfbfe

plugins:
  - serverless-offline

package:
  excludeDevDependencies: true

functions:
  hello:
    handler: src/index.handler
    events:
      - http:
          method: get
          path: hello
