service: lambda-enviroments

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  environment: ${file(./config/env.${self:provider.stage}.json)}
  iamRoleStatements: ${file(./config/serverless/db.iam.role.yml)}

custom:
  schedulerRate: rate(1 minute)
  enable: true
  tableName: ${self:provider.environment.DbTableName}
  dbReadCapacityUnits: ${self:provider.environment.DbReadCapacityUnits}
  dbWriteCapacityUnits: ${self:provider.environment.DbWriteCapacityUnits}

resources:
  Resources: ${file(./config/serverless/resources/dynamo.hero.table.yaml)}

functions:
  commit-message-scheduler:
    handler: handler.scheduler
    events:
      - schedule:
          rate: ${self:custom.schedulerRate}
          name: schedule-commit-message-${self:provider.stage}
          description: get commit message each minute
          enable: ${self:custom.enable}
