service: rekognito

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - rekognition:DetectLabels
      Resource: "*"
    - Effect: "Allow"
      Action:
        - translate:TranslateText
      Resource: "*"

functions:
  img-analisis:
    handler: handler.main
    events:
      - http:
          path: analyse
          method: get
